### ISSUE TITLE
Guzzle 7 support

### ISSUE THREAD

**Issue by AmitT** [avadev/AvaTax-REST-V2-PHP-SDK#119]
Trying to update guzzle on my project to 7.0.1 I got this error:

`$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - avalara/avataxclient 19.12.1 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.
    - avalara/avataxclient 19.11.0 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.
    - avalara/avataxclient 19.12.1 requires guzzlehttp/guzzle ~6 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for avalara/avataxclient ^19.11 -> satisfiable by avalara/avataxclient[19.11.0, 19.12.1].`

Can you please update, or allow us to update guzzle?

**Comment by dougfelton** [comment]
+1 here too.  Is there any plan to update to Guzzle 7?  Thank you!

**Comment by dwickander** [comment]
+1 also. Really could use the update to Guzzle 7.

**Comment by dwickander** [comment]
Is there a timeframe for updating the Guzzle dependency? I see there has been a pull request for quit some time - https://github.com/avadev/AvaTax-REST-V2-PHP-SDK/pull/123

**Comment by whobutsb** [comment]
@dwickander if you're interested I forked the repo and made a branch that updates the support for Guzzle 7.  

https://github.com/whobutsb/AvaTax-REST-V2-PHP-SDK
In your `composer.json` add the following lines:

```
    "repositories": [
        {
          "url": "https://github.com/whobutsb/AvaTax-REST-V2-PHP-SDK",
          "type": "vcs"
        }
    ],
```

**Comment by dwickander** [comment]
Thanks!

**Comment by p810** [comment]
+1

**Comment by maxicus** [comment]
+1

**Comment by singhofmarco** [comment]
This is actively preventing us from updating large parts of our dependencies. Many people would highly appreciate if you would make this change!

Thank you

**Comment by swdailey** [comment]
Another Laravel user chiming in - I think we'd all appreciate some developer feedback here, are we really expected to indefinitely stop upgrading our projects? While I thank @whobutsb for their fork, we absolutely need an official update.

**Comment by the-bham** [comment]
+1 
Laravel 7.0 has reached security EOL and now we cant put off upgrading to Laravel 8.0 too much longer.
