### ISSUE TITLE
How to CreateCustomers in PHP SDK

### ISSUE THREAD

**Issue by nishanthr93** [avadev/AvaTax-REST-V2-PHP-SDK#137]
![image](https://user-images.githubusercontent.com/48874622/113857977-cfc15100-97c0-11eb-97bf-e0d0af1e1013.png)

i can find only method of create function in the sdk but cant find the which parms need to be sent for create customers.

**Comment by akshit-avalara** [comment]
You can refer to the documentation: 
https://developer.avalara.com/api-reference/avatax/rest/v2/methods/Customers/CreateCustomers/
https://developer.avalara.com/api-reference/avatax/rest/v2/models/CustomerModel/
