### ISSUE TITLE
phpunit/phpunit should be in require-dev

### ISSUE THREAD

**Issue by bubnov-mikhail** [avadev/AvaTax-REST-V2-PHP-SDK#14]
"phpunit/phpunit" should be in require-dev of composer.json

It is not good to have phpunit on prod. Usually we use composer install --no-dev

**Comment by ted-spence-avalara** [comment]
Hi Bubnov,

We have added this change for the May release.  Our current release plans are May 2nd to Sandbox and May 8th to Production.  Full patch notes here: https://developer.avalara.com/blog/2017/04/25/AvaTax-17-5-patch-notes

**Comment by ted-spence-avalara** [comment]
Fixed with the May release.
