### ISSUE TITLE
Problem with psr-4 autoloader

### ISSUE THREAD

**Issue by bubnov-mikhail** [avadev/AvaTax-REST-V2-PHP-SDK#19]
You are using psr-4: "Avalara\\": "src/"
But all classes are living inside only one file: AvaTaxClient.php
If I am going to create an new AvaTaxClient() first - that is ok.
But if I want to use other classes (DocumentType, RefundTransactionModel, etc..) - I well got an error - psr-4 autoloader whould not find this class in Avalara/DocumentType.php

You should split classes in files to follow psr-4 or use "classmap" autoload.

**Comment by ted-spence-avalara** [comment]
Mikhail, is this issue now resolved with the improvements to the May release?

**Comment by bubnov-mikhail** [comment]
Seems so, thx!

04 авг 2017 г. 21:26 пользователь "Ted Spence" <notifications@github.com>
написал:
