### ISSUE TITLE
How can I set 'itemCode' for the line?

### ISSUE THREAD

**Issue by bubnov-mikhail** [avadev/AvaTax-REST-V2-PHP-SDK#21]
There is a method \Avalara\TransactionBuilder::withLine()
But I cannot pass itemCode value to it

**Comment by bubnov-mikhail** [comment]
If the transaction type is "SalesInvoice" - I get itemCode in response.
But I should not create a transaction with this type before user has accepted his bucket
But if I use SalesOrder and provide itemCode in lines - I get '' in response for each line..

Tested in https://sandbox-rest.avatax.com/swagger/ui/index.html#!/Transactions/CreateTransaction
Any idea?

**Comment by ted-spence-avalara** [comment]
Thank you for catching that!  I've merged your PR.  We will be preparing the May release shortly and it will include these changes.
