### ISSUE TITLE
Make optional REST parameters also optional in Client

### ISSUE THREAD

**Issue by michaeldoehler** [avadev/AvaTax-REST-V2-PHP-SDK#27]
Hi,

currently you require all options are be set in the client, e.g.

`public function queryUPCs($filter, $include, $top, $skip, $orderBy)`

But in the API reference all of these parameters are optional:

https://developer.avalara.com/api-reference/avatax/rest/v2/methods/Upcs/QueryUPCs/

So as developer you have to set these parameters also if there are not needed to be set.

**Comment by han8909227** [comment]
@michaeldoehler  
Thanks for noting that, we are in the progress of making optional parameters specified in https://rest.avatax.com/swagger/v2/swagger.json optional in the PHP method params.

**Comment by qjavalara** [comment]
Looks like this was resolved in https://github.com/avadev/AvaTaxClientLibrary/pull/58
