### ISSUE TITLE
Make Guzzle HTTP Client configuration extendable

### ISSUE THREAD

**Issue by michaeldoehler** [avadev/AvaTax-REST-V2-PHP-SDK#28]
Hi,

currently there is no way provided to extend Guzzle client configuration, e.g. adding a request logger.

I think the best option is to make the client "overwriteable", e.g. introduce some kind of getClient method and depend on this method instead of the private property, in this way you can easily extend the AvaTaxClient class and overwrite the client as you needed.

By the way, all parameters has to be protected instead of private in the client class to allow class extension.

**Comment by han8909227** [comment]
@michaeldoehler  Thanks for the suggestion, we are in the progress of making that happen

**Comment by han8909227** [comment]
@michaeldoehler I've opened a PR for this issue. Please verify that it has addressed your issue properly.  Thanks

**Comment by michaeldoehler** [comment]
Works well for me, thanks!
