### ISSUE TITLE
guzzle 6.3.0 ?

### ISSUE THREAD

**Issue by deckberg** [avadev/AvaTax-REST-V2-PHP-SDK#30]
says avalara/avataxclient 17.5.0.67 requires guzzlehttp/guzzle 5.*   but I have some other packages that use guzzle 6.3.0.  any plans to update avataxclient ?

**Comment by deckberg** [comment]
I see there is a merged fix that changes the requirement to ~6.0  not sure it that will work with guzzle 6.3.0 or if that will still fail.  maybe need to have it changed to ~6.*

**Comment by davidmpaz** [comment]
Hi,

Any news here. Any reason for not using updated major version ? 

Having same issue here.

**Comment by ted-spence-avalara** [comment]
Testing this with a PR: https://github.com/avadev/AvaTax-REST-V2-PHP-SDK/pull/54

**Comment by ted-spence-avalara** [comment]
We are updating the repository to support all 6.X versions of Guzzle.
