### ISSUE TITLE
Function not found in line 95 of TransactionBuilder.php

### ISSUE THREAD

**Issue by newelement** [avadev/AvaTax-REST-V2-PHP-SDK#35]
I think line 95 should be 

$l = $this->getMostRecentLine("WithItemDiscount");

**Comment by marcuswindecker** [comment]
I'm seeing the same thing.

`Call to undefined function Avalara\GetMostRecentLine()`

**Comment by marcuswindecker** [comment]
It looks like this has been updated on `master`, but it still incorrectly references `GetMostRecentLineIndex()` instead of the defined function `getMostRecentLineIndex()`. I've opened a PR to address this: #44.

**Comment by ted-spence-avalara** [comment]
Thank you for the PR!  Merged.
