### ISSUE TITLE
Add Method to TransactionBuilder to support adding Avalara\LineItemModel objects

### ISSUE THREAD

**Issue by caleywoods** [avadev/AvaTax-REST-V2-PHP-SDK#45]
I have some code I've added in my own file that is basically a duplicate of the `TransactionBuilder.php` file which accepts either a single instance of `LineItemModel` or an array of them. This gives flexibility to the end user to not be boxed in by needing to use the `withParameter()` method found [here](https://github.com/avadev/AvaTax-REST-V2-PHP-SDK/blob/master/src/TransactionBuilder.php#L131) to add parameters to the line items which cannot be set by one of the many methods already in the file to add line items to the TransactionBuilders internal `_model` array.

I will open a pull request in the next day or two so that this can be examined and I can provide the code that goes along with it to show how I am using it.

**Comment by ted-spence-avalara** [comment]
Believed resolved with merge of PR.  Thanks @caleywoods !
