### ISSUE TITLE
TransactionBuilder support for adding fields at the document level on CreateTransaction?

### ISSUE THREAD

**Issue by caleywoods** [avadev/AvaTax-REST-V2-PHP-SDK#48]
In experimenting with the API and the PHP SDK, I had a need to use some of the fields listed [here in the CreateTransactionModel](https://developer.avalara.com/api-reference/avatax/rest/v2/models/CreateTransactionModel/). In one case I wanted to use "exemptionNo" and saw no way with TransactionBuilder to add this. 

I see that there is a `withParameter()` method but the code for that places whatever is passed in into:

    $this->_model['parameters'][$name] = $value;

Where $name is what you passed into the method and $value is what you wish to set. 

I have already duplicated TransactionBuilder on my end to support some other functionality and I went ahead and created a `withDocumentParameter()` function that reads:

    $this->_model[$name] = $value;

So it's skipping the `'parameters'` part and sticking them right into the model, this seems to function just fine. I suppose `withParameter()` could be made to take a third argument of a boolean that defaults to false that controls whether it's added at the document level or within `'parameters'`. I know when I tried to set `exemptionNo` on my document with the `withParameter()` method the API told me that "exemptionNo" is an invalid parameter. 

According to the docs for CreateTransaction there is a "parameters" field that is optional and supports a list of things found when making a call to the `/api/v2/definitions/parameters` endpoint but I don't see the parameters in that list that would be of use.

Just wanted to gather input/feedback on this to see if it should be supported of if I am handling it incorrectly. I can open a PR with my additional function if need be.

**Comment by han8909227** [comment]
@caleywoods we believe this is resolved with your PR, please open another issue with there is any other issue if there is another issue you want to change. Thank you.

**Comment by caleywoods** [comment]
@han8909227 @ted-spence-avalara 

I don't think the PR that I had merged in handled this particular issue. I do have code that supports what I mention is wrong here. The previous PR dealt with adding line items into the TransactionBuilder as LineItemModels.

This issue was opened to gather feedback on how to address being able to add parameters to the Document level of the request during `CreateTransaction()` instead of into the `parameters[]` of the model being sent with the request.
