### ISSUE TITLE
Custom line number via SDK

### ISSUE THREAD

**Issue by antwaanvh** [avadev/AvaTax-REST-V2-PHP-SDK#57]
👋,

Via the API we are able to insert a custom line number. I do not see this functionality via the SDK.

I've attempted using `->withLineParameter('number', 'customNumber')`, but not matter what parameter I add *it's invalid*. Is there a list of `valid params`?
```
{"error":{"code":"InvalidParameter","message":"The parameter 'number' is not a valid parameter.","target":"IncorrectData (truncated...)\n
```

Any info on this is greatly appreciated.

**Comment by jondmcelroy** [comment]
The line parameter function does not add it to the line item model, but to a 'parameter' field in the line item model.

I also needed this functionality, made a PR here: https://github.com/avadev/AvaTax-REST-V2-PHP-SDK/pull/58

**Comment by jondmcelroy** [comment]
@han8909227 
I believe that he is referring to the number field on the line item:
https://developer.avalara.com/api-reference/avatax/rest/v2/models/LineItemModel/

Its only custom in thinking towards the SDK which forces it to an auto-incremented number behind the scenes.

**Comment by han8909227** [comment]
Hi @jondmcelroy @antwaanvh 
So in that case, the transactionBuilder is only meant to build out a transactionModel for you. In case of the transactionLineModel you would actually have to construct the model, which you can include a custom "number" property for your own reference. And add the transactionLineModel to your transactionModel through the transactionBuilder method `withLineItem()`

I hope this helps,
Han

**Comment by antwaanvh** [comment]
Thanks @jondmcelroy for clearing that up! 
@han8909227 I saw that in the source code and went with that approach, thanks! 🎉
