### ISSUE TITLE
TransactionBuilder is broken in 18.4 Release

### ISSUE THREAD

**Issue by danadesrosiers** [avadev/AvaTax-REST-V2-PHP-SDK#64]
TransactionBuilder::withCurrencyCode() is defined twice causing 
`Fatal error: Cannot redeclare Avalara\TransactionBuilder::withCurrencyCode()`

Looks like a merge error.

**Comment by han8909227** [comment]
@danadesrosiers Thanks for the catch

**Comment by danadesrosiers** [comment]
Thanks for merging the fix.

@ted-spence-avalara, can we expect a new release of 18.4 with this bug fix?

**Comment by ted-spence-avalara** [comment]
Believed resolved with https://github.com/avadev/AvaTax-REST-V2-PHP-SDK/releases/tag/18.4.4.191
