### ISSUE TITLE
Please use classmap autoloader in composer.json

### ISSUE THREAD

**Issue by bajoyasujoya** [avadev/AvaTax-REST-V2-PHP-SDK#66]
Your class file structure is not in PSR-4 format.

Example Avalara\AccountModel is in src/Models.php
for this class to be PSR-4, the file needs to be src/AccountModel.php all by itself.

Since you seem to generate Constants.php, Methods.php and Models.php, the autoloader section should say:

`
"autoload": {
    "classmap": ["src/"],
    "exclude-from-classmap": ["src/AvaTaxClient.php"]
}
`

This will create the mappings even for your generated files and also be automatically optimized.

**Comment by MissYeh** [comment]
OK - what seems to work is the following:

Add to composer.json:
```
"autoload": {
    "files": ["vendor/avalara/avataxclient/src/AvaTaxClient.php"]
},
```

Then run `composer dump-autoload` and et voila - it should load the multiclass files now
