### ISSUE TITLE
Missing method to set $this->_model['exemptionNo']

### ISSUE THREAD

**Issue by produktr** [avadev/AvaTax-REST-V2-PHP-SDK#70]
The class TransactionBuilder does not have a method to set the exemptionNo.

**Comment by han8909227** [comment]
Hi @produktr 
Thank you for raising the issue, I will discuss the issue with my team and get back to you.

Thanks,
Han

**Comment by han8909227** [comment]
Hi @produktr 
You should have access to the method `withExemptionNo` in the current version of this SDK.

**Comment by produktr** [comment]
Hi Han,


Thank you, I'll contact support to let them know the issue is resolved.

**Comment by qjavalara** [comment]
Looks like this issue was resolved. Closing.

**Comment by produktr** [comment]
Happy new year
