### ISSUE TITLE
Avatax php sdk giving zero tax in response to the API call.

### ISSUE THREAD

**Issue by Nethram** [avadev/AvaTax-REST-V2-PHP-SDK#95]
I have been trying with `PHP SDK` to get the tax rate. I noticed that for every request avatax api giving me zero tax. The reson for this one is I found that in the response `totalExempt` is set to the total amount i tried to get tax rate. I did not pass this exempt parameter with my request. Then how will this happen? My API call code looks like below,
`$tb = new Avalara\TransactionBuilder($client, "DEFAULT", Avalara\DocumentType::C_SALESORDER, 'ABC');
$t = $tb->withAddress('ShipFrom', '123 Main Street', null, null, 'Irvine', 'CA', '92615', 'US')
    ->withAddress('ShipTo', '100 Ravine Lane', null, null, 'Bainbridge Island', 'WA', '98110', 'US')
   ->withLine(40.21, 1, null, PC040400)
   ->create();
echo('<h2>Transaction #2</h2>');
echo('<pre>' . json_encode($t, JSON_PRETTY_PRINT) . '</pre>');`

My response looks like(this is not for the same request but all response looks like this. Look at the `totalExempt` and `totalAmount`),

`Transaction #1
{
    "id": 0,
    "code": "7a89a8fb-be32-4cc6-8408-a12feb7d4ba9",
    "companyId": 211434,
    "date": "2019-05-20",
    "paymentDate": "2019-05-20",
    "status": "Temporary",
    "type": "SalesOrder",
    "customerVendorCode": "EXAMPLECUSTOMER",
    "customerCode": "EXAMPLECUSTOMER",
    "reconciled": false,
    "totalAmount": 40.21,
    "totalExempt": 40.21,
    "totalDiscount": 0,
    "totalTax": 0,
    "totalTaxable": 0,
    "totalTaxCalculated": 0,
    "adjustmentReason": "NotAdjusted",
    "locked": false,
    "version": 1,
    "exchangeRateEffectiveDate": "2019-05-20",
    "exchangeRate": 1,
    "modifiedDate": "2019-05-20T05:04:16.4602473Z",
    "modifiedUserId": 236613,
    "taxDate": "2019-05-20T00:00:00",
    "lines": [
        {
            "id": 0,
            "transactionId": 0,
            "lineNumber": "1",
            "discountAmount": 0,
            "exemptAmount": 40.21,
            "exemptCertId": 0,
            "isItemTaxable": true,
            "lineAmount": 40.21,
            "quantity": 1,
            "reportingDate": "2019-05-20",
            "tax": 0,
            "taxableAmount": 0,
            "taxCalculated": 0,
            "taxCode": "PC040400",
            "taxCodeId": 5197,
            "taxDate": "2019-05-20",
            "taxIncluded": false,
            "details": [
                {
                    "id": 0,
                    "transactionLineId": 0,
                    "transactionId": 0,
                    "country": "US",
                    "region": "CA",
                    "exemptAmount": 0,
                    "jurisCode": "06",
                    "jurisName": "CALIFORNIA",
                    "stateAssignedNo": "",
                    "jurisType": "STA",
                    "jurisdictionType": "State",
                    "nonTaxableAmount": 40.21,
                    "rate": 0,
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "Use",
                    "taxName": "CA STATE TAX",
                    "taxAuthorityTypeId": 45,
                    "taxCalculated": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "isNonPassThru": false
                }
            ],
            "nonPassthroughDetails": [],
            "hsCode": "",
            "costInsuranceFreight": 0,
            "vatCode": "",
            "vatNumberTypeId": 0
        }
    ],
    "addresses": [
        {
            "id": 0,
            "transactionId": 0,
            "boundaryLevel": "Address",
            "line1": "2000 Main Street",
            "line2": "",
            "line3": "",
            "city": "Irvine",
            "region": "CA",
            "postalCode": "92614",
            "country": "US",
            "taxRegionId": 4017409,
            "latitude": "33.684689",
            "longitude": "-117.851495"
        },
        {
            "id": 0,
            "transactionId": 0,
            "boundaryLevel": "Address",
            "line1": "255 S. King Street",
            "line2": "",
            "line3": "",
            "city": "Seattle",
            "region": "WA",
            "postalCode": "98104",
            "country": "US",
            "taxRegionId": 1048894,
            "latitude": "0",
            "longitude": "0"
        }
    ],
    "summary": [
        {
            "country": "US",
            "region": "CA",
            "jurisType": "State",
            "jurisCode": "06",
            "jurisName": "CALIFORNIA",
            "taxAuthorityType": 45,
            "stateAssignedNo": "",
            "taxType": "Use",
            "taxName": "CA STATE TAX",
            "rateType": "General",
            "taxable": 0,
            "rate": 0,
            "tax": 0,
            "taxCalculated": 0,
            "nonTaxable": 40.21,
            "exemption": 0
        }
    ]
}`

**Comment by contygm** [comment]
While transactions exemptions can be controlled by the user in certain cases, you also get exempt amounts in jurisdictions where you have not enabled nexus for tax calculation. The PHP SDK is behaving as normal and will apply the California tax rate for companies with nexus in that state. 

Please check the nexus of your company and add California to see the appropriate tax calculations. If you need help turning on your nexus, please reach out on [our forums](https://community.avalara.com/avalara) or checkout our [related documentation](https://developer.avalara.com/api-reference/avatax/rest/v2/methods/Nexus/).
